"""Vesta protocol client library for Python."""

__version__ = "0.1.3"

from vesta_client.connection import VestaConnection
from vesta_client.events import create_event
from vesta_client.federation import (
    DiscoverableApp,
    DiscoveredRelay,
    FederationClient,
    ServerDescriptor,
    build_descriptor_signing_input,
    verify_descriptor,
)
from vesta_client.identity import (
    VestaIdentity,
    load_identity_extra,
    load_or_create_identity,
    save_identity_extra,
)
from vesta_client.device_groups import (
    ANNOUNCE_EVENT_TYPE,
    DeviceGroup,
    DeviceGroupProjection,
    LINK_EVENT_TYPE,
    PROTOCOL_CHANNEL_PREFIX,
    PairingPayload,
    UNLINK_EVENT_TYPE,
    build_announce,
    build_link,
    build_unlink,
    device_group_channel,
    generate_group_id,
    is_protocol_channel,
)
from vesta_client.projections import (
    AppendOnlyLog,
    EventReducer,
    LwwMap,
    LwwMapUpdate,
    LwwRegister,
    ProjectionCheckpoint,
    ProjectionSnapshot,
    SnapshotNotSupportedError,
)
from vesta_client.projection_store import (
    InMemoryProjectionStore,
    ProjectionStore,
    SqliteProjectionStore,
    restore_projection,
    save_projection,
)
from vesta_client.limits import (
    ErrorClassification,
    VestaErrorCodes,
    VestaLimitNotice,
    classify_error_code,
)
from vesta_client.relay import (
    RELAY_MANIFEST_EVENT_TYPE,
    EscapeFallback,
    FileManifestStore,
    FileRelayOverrideStore,
    InMemoryManifestStore,
    InMemoryRelayOverrideStore,
    ManifestStore,
    RelayDirectory,
    RelayEndpoint,
    RelayManifest,
    RelayOverrideStore,
    VestaAppConfig,
    build_manifest_signing_input,
    manifest_channel_for,
    resolve_relay_candidates,
    sign_manifest,
    verify_manifest,
)
from vesta_client.signing import build_signing_input, sign_event
from vesta_client.storage import (
    ClientEventStore,
    InMemoryClientEventStore,
    OutboxEntry,
    OutboxStatus,
    SqliteClientEventStore,
)
from vesta_client.types import (
    AckMessage,
    ErrorMessage,
    EventMessage,
    EventsBatchMessage,
    SequencedEvent,
    ServerMessage,
    VestaEvent,
    WelcomeMessage,
)

__all__ = [
    "__version__",
    "AckMessage",
    "ANNOUNCE_EVENT_TYPE",
    "AppendOnlyLog",
    "ClientEventStore",
    "DeviceGroup",
    "DeviceGroupProjection",
    "DiscoverableApp",
    "DiscoveredRelay",
    "ErrorClassification",
    "ErrorMessage",
    "EscapeFallback",
    "EventMessage",
    "EventReducer",
    "EventsBatchMessage",
    "FederationClient",
    "FileManifestStore",
    "FileRelayOverrideStore",
    "InMemoryClientEventStore",
    "InMemoryManifestStore",
    "InMemoryProjectionStore",
    "InMemoryRelayOverrideStore",
    "LINK_EVENT_TYPE",
    "LwwMap",
    "LwwMapUpdate",
    "LwwRegister",
    "ManifestStore",
    "OutboxEntry",
    "OutboxStatus",
    "PROTOCOL_CHANNEL_PREFIX",
    "PairingPayload",
    "ProjectionCheckpoint",
    "ProjectionSnapshot",
    "ProjectionStore",
    "RELAY_MANIFEST_EVENT_TYPE",
    "RelayDirectory",
    "RelayEndpoint",
    "RelayManifest",
    "RelayOverrideStore",
    "SequencedEvent",
    "ServerDescriptor",
    "ServerMessage",
    "SnapshotNotSupportedError",
    "SqliteClientEventStore",
    "SqliteProjectionStore",
    "UNLINK_EVENT_TYPE",
    "VestaAppConfig",
    "VestaConnection",
    "VestaErrorCodes",
    "VestaEvent",
    "VestaIdentity",
    "VestaLimitNotice",
    "WelcomeMessage",
    "build_announce",
    "build_descriptor_signing_input",
    "build_link",
    "build_manifest_signing_input",
    "build_signing_input",
    "build_unlink",
    "classify_error_code",
    "create_event",
    "device_group_channel",
    "generate_group_id",
    "is_protocol_channel",
    "load_identity_extra",
    "load_or_create_identity",
    "manifest_channel_for",
    "resolve_relay_candidates",
    "restore_projection",
    "save_identity_extra",
    "save_projection",
    "sign_event",
    "sign_manifest",
    "verify_descriptor",
    "verify_manifest",
]
